# Source: https://github.com/lightninglabs/lndmon/blob/master/prometheus.yml
# Copied into prometheus container

scrape_configs:
  - job_name: 'lndmon'
    scrape_interval: '20s'
    static_configs:
      - targets: ['lndmon:9092']
  - job_name: 'lnd'
    scrape_interval: '20s'
    static_configs:
      - targets: ['${LND_HOSTNAME}:${MONITORLISTEN}']
