version: '3.7'
services:
  # btc is an image of bitcoin node which used as base image for btcd and
  # btccli. The environment variables default values determined on stage of
  # container start within starting script.
  btc: &btc
    image: btcd
    user: ${UID}:${GROUPS}
    build:
      context: ../docker/btcd/
    volumes:
      - shared:/rpc
      - bitcoin:/data
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
    networks:
      - boltbox

  btcd:
    <<: *btc
    container_name: btcd
    environment:
      - DEBUG
      - MINING_ADDRESS
      - NETWORK
    entrypoint: ['./start-btcd.sh']
    ports:
      ## Comment these if they conflict with something else you're running.
      #-- Mainnet
      - '8333:8333'
      - '8332:8332' # RPC
      - '8334:8334' # Wallet
      #-- Testnet
      - '18333:18333'
      - '18332:18332' # RPC
      - '18334:18334' # Wallet
      #-- Regtest
      - '48444:48444'
      - '48332:48332' # RPC
      - '48334:48334' # Wallet
      #-- Simnet
      - '18555:18555'
      - '18556:18556' # RPC
      - '18558:18558' # Wallet

  btcctl:
    <<: *btc
    container_name: btcctl
    links:
      - 'btcd:rpcserver'
    entrypoint: ['./start-btcctl.sh']

  lnd: &lnd
    image: lnd-boltbox
    user: ${UID}:${GROUPS}
    build:
      context: ../docker/lnd/
      dockerfile: Dockerfile
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - CHAIN
      - DEBUG
      - RPCLISTEN
      - RESTLISTEN
      - LISTEN
      - LND_DIR
    volumes:
      - shared:/rpc
      - lnd:/lnd-data
    networks:
      - boltbox

  lnd_btc: &lnd_btc
    <<: *lnd
    container_name: lnd_btc
    links:
      - 'btcd:blockchain'

  lncli:
    <<: *lnd
    container_name: lncli
    entrypoint: ['./start-lncli.sh']
    stdin_open: true

  rtl:
    container_name: simnet_rtl
    image: rtl-boltbox
    build:
      context: ../docker/rtl/
      args:
        RTL_VERSION: 0.5.4
    ports:
      - ${RTL_PORT?}:${RTL_PORT?}
    environment:
      - PORT=${RTL_PORT?}
      - RTL_PASS
      - LND_SERVER_URL
      - MACAROON_PATH
      - NODE_AUTH_TYPE
      - LND_CONFIG_PATH
      - RTL_CONFIG_PATH
      - BITCOIND_CONFIG_PATH
      - RTL_SSO=0
      - RTL_COOKIE_PATH
      - LOGOUT_REDIRECT_LINK
      - CHANNEL_BACKUP_PATH
    volumes:
      - lnd:/lnd-data
    networks:
      - boltbox

  boltwall:
    container_name: simnet_boltwall
    image: boltwall:boltbox
    build:
      context: ../docker/boltwall
    ports:
      - 8000:8000
    environment:
      - BOLTWALL_PORT=8000
      - LND_TLS_CERT
      - LND_MACAROON
      - LND_SOCKET
      - CAVEAT_KEY=12345
      - SESSION_SECRET
      - BOLTWALL_TIME_CAVEAT
    networks:
      - boltbox
    volumes:
      - ./configs:/boltwall/configs

networks:
  boltbox:
    name: boltbox-simnet

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # lnd volume for maintaining lnd wallet persistence
  # during container recreation.
  lnd:
    driver: local
    name: lnd-data-simnet
